### ISSUE TITLE
DB Client

### ISSUE THREAD

**Issue by geospatial-roman** [eodcgmbh/openeo-fastapi#10]
Add Client based on SQL Alchemy to communicate with DB.

**Comment by SerRichard** [comment]
Will take a look at this, seen a package I think would work nicely for us

http://docs.peewee-orm.com/en/latest/index.html

Should be able to create a database from the defined models using this, I am not sure about how it would handle a revision in the same way as alembic though.

Might be okay, but it would mean more work on the developer when wanting to revision the database, and include new model changes. Will take a look and see if I can produce something usable from there or not!

**Comment by SerRichard** [comment]
PeeWee didn't do as hoped, stuck with sqlalchemy!
