### ISSUE TITLE
Error validating OIDC_POLICIES

### ISSUE THREAD

**Issue by micafer** [eodcgmbh/openeo-fastapi#59]
There is an error in this function:

https://github.com/eodcgmbh/openeo-fastapi/blob/77c499c5e5f43d2be1d99bd85aa38408c0a90e4b/openeo_fastapi/client/settings.py#L68

As v is an string this for get every single character of the string, so it does not work as expected.

**Comment by SerRichard** [comment]
It should work, there is a config function lower in the page which converts the env variable to a list, for some reason, this is not running. I'll update the code to re-apply the variable cleaning to make sure v is a list. Additionally, the cleaning will now disregard empty strings, so the policies will become an empty list. This should resolve the issues.

That being said, I may have to take a look at why the variable is not being cleaned correctly, this may cause problems later down the line if the same occurs in the stac_collections_whitelist setting. I'll update again here when the MR is ready.

**Comment by SerRichard** [comment]
It will be resolved with #60 . I will pull this to the openeo_argoworkflows repo and make a new release. Expect an updated version later this afternoon.
